#!/bin/bash

#SBATCH --partition=GENOA
#SBATCH --nodes=1
#SBATCH --account=dssc
#SBATCH --ntasks-per-node=2
#SBATCH --cpus-per-task=8
#SBATCH --mem=50G
#SBATCH --output=oversampling_tuning.out
#SBATCH --time=01:00:00

$SLURM_JOB_ID

echo "========================"
echo "running on:       $(hostname)"
echo "job_id            $SLURM_JOB_ID"
echo "directory:        $(pwd)"
echo "date:             $(date)"
echo "========================"

cd
cd uni/Parallel-Sample-Sort/Parallel/

module load mpi/latest

make clean
make
make oversampling_tuning

echo "========================"
echo "finished work"
echo "finish date:      $(date)"
echo "========================"