#!/bin/bash

#SBATCH --partition=GENOA
#SBATCH --nodes=2
#SBATCH --account=dssc
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=60G
#SBATCH --output=o.out
#SBATCH --time=01:00:00

$SLURM_JOB_ID

echo "========================"
echo "running on:       $(hostname)"
echo "job_id            $SLURM_JOB_ID"
echo "directory:        $(pwd)"
echo "date:             $(date)"
echo "========================"

module load mpi/latest

make clean
make
make run

echo "========================"
echo "finished work"
echo "finish date:      $(date)"
echo "========================"
