#!/bin/bash

#SBATCH --partition=GENOA
#SBATCH --nodes=1
#SBATCH --account=dssc
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=64
#SBATCH --mem=30G
#SBATCH --output=sorting_comparison.out
#SBATCH --time=01:00:00

$SLURM_JOB_ID

echo "========================"
echo "running on:       $(hostname)"
echo "job_id            $SLURM_JOB_ID"
echo "directory:        $(pwd)"
echo "date:             $(date)"
echo "========================"

cd
cd uni/Parallel-Sample-Sort/Parallel/

module load mpi/latest

make clean
make
make sorting_comparison
make sorting_comparison
make sorting_comparison
make sorting_comparison

echo "========================"
echo "finished work"
echo "finish date:      $(date)"
echo "========================"
